name: Deploy
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
    - master
env:
  WORKING_DIRECTORY: BlazorSchoolDocs
  VPS_WEB_DIRECTORY: /home/blazorschool_redesign/wwwroot/contents
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy web via ssh
      uses: garygrossgarten/github-action-scp@master
      with:
        local: contents
        remote: ${{ env.VPS_WEB_DIRECTORY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}